### ISSUE TITLE
not able to configure properties in doLast of plugin task

### ISSUE THREAD

**Issue by akmalick** [node-gradle/gradle-node-plugin#108]
I have noticed that gradle-node-plugin doesnot allow configuring any property in a doLast closure.

```
task  npmInstallPkg(type: NpxTask){
    doLast{
        //install node packages from package.json
        dependsOn npmInstall

        //install pkg globally
        command = 'npm'
        args = ['install', '-g', 'pkg']
    }
}
```

Trying to execute above task leads to below error:

```
A problem was found with the configuration of task ':npmInstallPkg'.
> No value has been specified for property 'command'.
```

From what I understand, the gradle node plugin is not able to get the property **command** for Task NpxTask during the configuration phase. If this is the case, then it makes total sense to me.

But, how do I make sure that my npm commands don't get executed during the configuration phase itself. I want to be in-charge of the task and want it to be triggered during the execution phase i.e I want to be able to trigger it lazily.

**Comment by bsautel** [comment]
I am not sure I understand what you are trying to do.

But what is wrong in your code is that you configure the task **after** its execution. `doLast` enables us to add some actions at the end of the task execution.

In Gradle, when you define a task, it does not mean it is going to run. It only tells Gradle that there is a task with a given name and how to run it if needed. It will run only if you ask Gradle to run it or if you as Gradle to run a task that depends (directly or not ) on it.

Writing that is perfectly valid:

```groovy
task  npmInstallPkg(type: NpxTask){
    //install node packages from package.json
    dependsOn npmInstall

     //install pkg globally
    command = 'npm'
    args = ['install', '-g', 'pkg']
}
```
This will run if you run `gradle npmInstallPkg`. And as it depends on `npmInstall`, it will run `npmInstall` first.

When Gradle runs, it first runs the configuration phase: it executes the build script (which applies plugins, defines tasks, configurations, ...). At the end of this phase, Gradle gets a set of tasks that can be executed. Then, there is the execution phase. In this phase, it will execute the tasks it was asked to run: the tasks directly asked (`clean` and `build` for `gradle clean build`) but also all their dependency tree. For instance when you `build` a Java project, you have to run `compileJava` then `run`, then `compileTestJava`, `test` and many other tasks.

I also noticed that you use `npm install -g pkg`. I don't know what you are trying to do, but I would recommend you not doing that:
* Because on some environments it will probably won't work (when using the Node.js package of a Linux distribution, you will probably need to be root to run that)
* You can have only one version of the command globally installed ; if you want to build several branches that don't use the same version on the same host, you will have some issues

I would rather install it locally by adding it in the `package.json` dependencies. When you want to run it, of course you will not be able to run `pkg`. But you will be able to run `npx pkg` or run it via Gradle with the `NpxTask` to which you ask to run the `pkg` command.

**Comment by akmalick** [comment]
@bsautel  I'm really sorry if I made it confusing for everyone. This [question-in-gradle-forum](https://discuss.gradle.org/t/what-is-dolast-for/27731) is very much related to my issue, especially this [comment-in-gradle-forum](https://discuss.gradle.org/t/what-is-dolast-for/27731/2) explains my problem statement very well.

It's my bad that I couldn't see the forest for the trees. I didn't try the task without doLast. I was under the assumption that if I do not provide the **doLast** for **npmInstallPkg** task, it would automatically be executed during the configuration phase i.e. without me explicitly calling it. I did try by removing the doLast after your suggestion and it works as per expectation.

This would get called from Jenkins which is on Windows Server. So far it has been working fine. I believe minimum required permissions are already granted.

Really appreciate your response.
Thank you so much.
Lessons learnt. :)

**Comment by bsautel** [comment]
Ok, I understand. In fact what you write in the `task` block is the task configuration. This is executed at configuration time. If you want to add an extra action that the task should execute at runtime, you cannot write it in the configuration block, since it will be executed at configuration time.

The code you wrote in the task block is the task configuration. It **must** be executed at configuration time and not at runtime.

Note that there Gradle now proposes a [task avoidance configuration mechanism](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) and recommends to use it to speed up the build. The principle is simple: the configuration blocks of the tasks are executed only if the task needs to be executed (lazily). If the task does not need to be executed, there is no need to configure it so it does not execute its configuration. This means that the configuration block will no longer be always executed. But this does not change anything to the `doFirst` and `doLast` semantics, these hooks are still executed at runtime.

**Comment by akmalick** [comment]
@bsautel  That is some very great piece of advice you have given. Thank you so much. This has been a great learning for me.
