### ISSUE TITLE
Add success and failure hooks to tasks

### ISSUE THREAD

**Issue by henrik242** [node-gradle/gradle-node-plugin#144]
YarnTask 2.2.4 had a result method:
```
    @Internal
    ExecResult getResult()
    {
        return this.result
    }
```

This is gone from 3.0.0, is there any other way to access the result?

**Comment by henrik242** [comment]
Usage example:

     val jsCodeStyle by tasks.registering(YarnTask::class) {
        ...
        doLast {
            if (result?.exitValue != 0) {
                reportFile.forEachLine {
                    logger.lifecycle(it)
                }
            }
            result?.assertNormalExitValue()
        }
    }

**Comment by bsautel** [comment]
I removed all the `result` fields from the tasks for multiple reasons:
- I saw that as an antipattern (this adds a state to the tasks that do not have any state)
- I did not see any use case of this field (but I am a relatively new contributor on this project, I don't know all the history and why those fields were present)
- accessing this field from another task is not reliable because, even if a task A depends on a task B, there is no guarantee that the task B ran just before (it can be up-to-date) and in this case its `result` field will be null - note that as you do that in the `doLast` hook and thus you are sure that the task just comes to run

But your use case seems to make sense, and I don't see any way to do that without using the `result` field.

Sorry for this breaking change that we did not mention in the changelog.

I just have one question: is this line necessary? `result?.assertNormalExitValue()`

By default the `ignoreExitValue` field is `false`, so the task will fail if the `yarn` exit value is not `0`. But maybe you set it to `true` and check it yourself because otherwise the task fails and the `doLast` hook is not executed (I don't remind exactly how the `doLast` hook behaves when the task fails)?

@deepy what do you think we should do? Should we reintroduce the `result` field? Do you see any other way to do that without storing a state into the tasks?

**Comment by deepy** [comment]
My mind is a bit fuzzy, fell with my dog while out walking, but I can think of another use-case for it and that's test results.
e.g. it doesn't seem unreasonable to me that there'd be some test framework that returns 0 on success, 1 on unstable, and 2 on failure (or something similar)

but for the given task, either this approach or something like https://stackoverflow.com/a/44941856 seems sensible.

though with this in mind, it probably makes sense to reintroduce the results or at least the exit code

**Comment by henrik242** [comment]
> I just have one question: is this line necessary? result?.assertNormalExitValue()

I did that because I also had

               execOverrides {
                    isIgnoreExitValue = true
                    standardOutput = reportFile.outputStream()
                }

**Comment by deepy** [comment]
I read somewhere that `doLast` won't trigger if the task fails, so this sounds like a workaround for that

**Comment by bsautel** [comment]
@deepy , hope that you are fine!

Thanks, that confirms what I thought for the `doLast` hook.

What if we add two hooks on all the tasks: `onSuccess` and `onFailure`?

```kotlin
val reportFile = [...]
val jsCodeStyle by tasks.registering(YarnTask::class) {
  execOverrides {
    standardOutput = reportFile.outputStream()
  }
  onFailure {
    reportFile.forEachLine {
      logger.lifecycle(it)
    }
  }
}
```

**Comment by deepy** [comment]
We're both fine but a bit exhausted :dog2: 

If we're adding hooks we should expose the exit code to `onFailure` (or possibly create a third one with it available) but it sounds like a good addition!

**Comment by bsautel** [comment]
Yes, we should expose the exit code or even the `ExecResult` to both `onSuccess` and `onFailure` hooks. That should enable @henrik242 to fix this issue and that does not add any state to the tasks.

**Comment by henrik242** [comment]
@bsautel That looks excellent. 

@deepy Hope you are recovering well!

**Comment by bsautel** [comment]
I just come to make some experiments.

We cannot pass the `ExecResult` to the `onFailure` hook because this hook is triggered if the `exec` method throwed an exception and thus did not return the `ExecResult`. The exception thrown is `org.gradle.process.internal.ExecException` from an internal package of Gradle and it does not contain any `ExecResult`.

Should we handle the `ignoreExitValue` ourselves? I mean always set it to true in the `exec` method, get the `ExecResult` and check ourselves the status code if the `ignoreExitValue` is `false`. In this case we would be able to pass the `ExecResult` to the `onFailure` hook. This should work, but if conflicts with the `execOverrides` configuration in which this property can be overridden and could cause the hook not to be triggered if we work this way. Note that other cause could make the task fail and in this case we would not have any `ExecResult` to pass to the hook.

What do you think about that @deepy and @henrik242?

**Comment by deepy** [comment]
Maybe we can pass something like an `Either<Exception, ExecResult>`?

Especially if we know that we're either going to fail and get an exception or we're going to get a result

**Comment by henrik242** [comment]
Or maybe an object with both exception and execResult fields?

**Comment by bsautel** [comment]
Thanks for your feedback, that will help me to build something better. I'll work on that when I have some time.

**Comment by henrik242** [comment]
Great! I'll try not to hold my breath waiting ;)

**Comment by bsautel** [comment]
I pushed a branch containing a first version of these hooks in the `task-hooks` branch.

For now, the `onSuccess` hook takes the `ExecResult` as parameter. The `onFailure` hook takes the `Exception` as parameter.

I could not find a way to get the `ExecResult` when we would like it to be available (for instance when the exit status is not valid). I can do that when using the `ignoreExitValue` property but not when customizing this value in the `execOverrides`. What I would want to do is to always ignored the exit value whatever the configuration is. If it was not configured to ignore exit value, we ask to check the exit value. But I don't know how to make that if the user overrides it using `execOverrides`. Any idea?

**Comment by henrik242** [comment]
Great work! I have no idea how to help with the execOverrides sitution, I'm afraid :/

**Comment by bsautel** [comment]
I did multiple improvements to my initial proposition.

All the hooks are grouped into a `hooks` property:
```gradle
hooks {
    onSuccess {
    }
    onFailure {
    }
}
```

The behavior of the `onFailure` hook changed. It is now called only when the command exited with an error exit status and the task was not configured to ignore exit status. It received the `ExecResult` that contains the `exitStatus`.

For that I had to change the behavior of the `ExecRunner`. It now always call the Gradle exec API with ignore exist status true, even if it is configured to false in the task. The check is done later by the task itself. That's not a big deal, but this prevents configuring `ignoreExitStatus` from `execOverrides` from working (which is not the recommended way to do since all the task have an `ignoreExitValue` property).

I also added a `onExecFinished` hook that is called just after the command execution. It enables for instance to fail the build if the exit code is not the expected one. For instance if we want to task to success only if the exit status is `5` we can do that:
```gradle
task myTask(NodeTask) {
    // task configuration
    ignoreExitStatus = true
    hooks {
        onExecFinished {
            if (it.exitStatus != 5) { throw new IllegalStateException("Wrong exit status") }
        }
    }
}
```

@deepy and @henrik242 what do you think about those changes?

**Comment by henrik242** [comment]
@bsautel That sounds good as far as I can see!

**Comment by deepy** [comment]
Still recovering from a fever, but it looks good 👍

**Comment by bsautel** [comment]
Thanks @henrik242 and @deepy for your feedback. I am going to write the documentation for this feature and then I will merge this branch.

@deepy Hope you'll be fine very soon!

**Comment by JamesXNelson** [comment]
I'm really curious as to WHY the `result` field was removed.  "I see state on tasks as an anti-pattern".... ........tasks are inherently stateful objects. They literally have a `state` field describing their current state.  Even if you feel stateless programming is superior, removing fields from production code b/c you don't think people will need them is ...a bit reckless (we were using this field, somewhat heavily).

Our use cases are that we want to run NpmTask as part of our tests.  We don't want one failure to completely kill the build, instead we want to collect up all our failures and wait until the end of the build to fail.  We used the result object to figure this out, and in a few cases, we inspected the results to print workaround / additional help to the user if they were hitting issues w/ known fixes.

Anyway, it sounds like there's a plan to get this information back somehow?  I'd prefer the field back, but anything that can be accessed to determine success/failure codes would be enough for us to survive, bonus if we can see the stdout/stderr.

PS - finalizedBy is always run after a task, whether it succeeds or fails. You may find it works better than doLast in some situations.

**Comment by JamesXNelson** [comment]
Any chance this can get picked back up? I know a thing or two about gradle plugin development, would be happy to contribute if it meant we can get a fix out.  Our company is unable to complete a big upgrade b/c we needed a newer version of this plugin after the `result` field was taken away; all our integration testing cannot proceed without getting this back in some way.  Please let me know how I can help to expedite this fix.

**Comment by deepy** [comment]
I did another try at merging the `task-hooks` but unfortunately master has gone quite some ways.

The biggest changes are moving things from private class methods to public functions and the addition of a base task class: `BaseTask` which conflicts with the addition of a base task class `AbstractNodeExecTask`

If anyone wants to give it a try and submit a PR or make a new PR that reintroduces the state I'll happily work with either PR

**Comment by deepy** [comment]
related to https://github.com/node-gradle/gradle-node-plugin/issues/237
