### ISSUE TITLE
Consider dropping Gradle 5.6.4 support

### ISSUE THREAD

**Issue by deepy** [node-gradle/gradle-node-plugin#159]
Full context available in #158

But with Gradle 7 having release rc1 we now have a longer test runtime as we test for version `5.6.4`, `6.0`, `6.8.3` and `7.0-rc1`.

We want to test for Gradle 7 and we don't want to stop testing the earliest and current versions of Gradle 6 as it's the currently supported major, this leaves dropping `5.6.4`

Having looked at the code I did misremember, the part I want to remove would mean dropping support for Gradle < 6.6.

Another alternative would perhaps be to create a GHA only for running the old platforms, perhaps testing `5.6.4` and `6.0` and on linux only, leaving the win+linux+mac tests with current + latest

**Comment by bsautel** [comment]
I think that we can indeed stop testing with different Gradle versions in GHA on Windows and macOS which are significantly slower than Linux.

We also may not need to run all integration tests using different Gradle versions. Maybe we can select a smart subset of them that is enough representative of what the plugin does. But I'm not sure we can significantly reduce the amount of tests to run because each integration test tests a specific feature. I have to think about that.

For now, as a first step, I suggest we run only the tests using multiple versions on Linux GHA.

And regarding dropping support of 5.6.4, does somebody know whether there are some Gradle version usage statistics?

**Comment by deepy** [comment]
Build Services gets introduced in Gradle 6.1 (released 2020/01) so maybe now is the time to drop support for 5.6.4 (released 2019/11)
