### ISSUE TITLE
IntelliJ "Build Project" create "yarn.lock" file and "node_modules" on project's root.

### ISSUE THREAD

**Issue by wonsuc** [node-gradle/gradle-node-plugin#162]
My project is `Spring Boot` with `React.js` in same project folder with `IntelliJ`.

If I set "Gradle" to build option in the setting,  
(Settings -> Build, Excution, Deployment -> Build Tools -> Gradle -> Build and run -> "Gradle")

It creates `yarn.lock` file and `node_modules` on project root directory.  
`node_modules` folder only contains a `.yarn-integrity` file. 

This doesn't happen when I run `gradle build` to create `*.jar` file for the project.  

This is the `task` which create those files and folder.

```
task appYarnBuild(type: YarnTask) {
    def command = ''
    if (!serverProfileConfig) {
        println('Server Profile Config is not defined.')
        return
    }
    if (serverProfileConfig.isLocal) command = 'build:development'
    if (serverProfileConfig.isDev) command = 'build:development-integrated'
    if (serverProfileConfig.isProd) command = 'build:production'
    description = "Builds production version of the webapp"
    workingDir = file("${project.projectDir}/src/main/webapp/react")

    args = ["run", command]
}

compileJava.dependsOn appYarnBuild
```

This is a gradle log.

```
AM 10:30:19: Executing tasks ':classes :testClasses'...

Configuration on demand is an incubating feature.

> Configure project :
compileJava
bootWar
Server Profile Config is not defined.
15.0.1 (Amazon.com Inc. 15.0.1+9)
jrt:/java.base/java/lang/Object.class

> Task :nodeSetup SKIPPED
> Task :yarnSetup UP-TO-DATE

> Task :appYarnBuild
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.17s.

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE

BUILD SUCCESSFUL in 5s
5 actionable tasks: 1 executed, 4 up-to-date
AM 10:30:25: Tasks execution finished ':classes :testClasses'.
```

**Comment by bsautel** [comment]
Do you use the `yarn` task to install dependencies? Who is responsible of adding dependencies?

Which IntelliJ command do you run when your problem occurs?

Also, for your information, you can find [here](https://github.com/node-gradle/gradle-node-plugin/tree/master/examples/vertx-react) an example of a Gradle build that embeds a React application built by Yarn into a Vert.x application.

You can also maybe have a look to [this example](https://github.com/node-gradle/gradle-node-plugin/tree/master/examples/spring-boot-angular) since it shows how to embed an Angular application built by npm into a Spring Boot application. The Spring Boot part may be interesting for you.

**Comment by wonsuc** [comment]
> Do you use the yarn task to install dependencies? Who is responsible of adding dependencies?  

I followed this [blog](https://blog.indrek.io/articles/serving-react-apps-from-spring-boot), so my codes are based on the author's code. My yarn task simply calls scripts that are defined in the `package.json` file. 

> Which IntelliJ command do you run when your problem occurs?

"Build Project", the shortcut is Ctrl + F9

> Also, for your information, you can find here an example of a Gradle build that embeds a React application built by Yarn into a Vert.x application.
> 
> You can also maybe have a look to this example since it shows how to embed an Angular application built by npm into a Spring Boot application. The Spring Boot part may be interesting for you.

Thank you for the examples.  

I suspect the `return` command in my yarn task.  
What is going to happen if I just quit the yarn task with the `return` command? (before defining workingDir, args...)

**Comment by bsautel** [comment]
In the case of the `return` execution, the `YarnTask` will remain unconfigured and it will probably run an empty command, so the `yarn` command (not 100% sure about that). This could explain why you get a `node_modules` directory.

I don't know how `serverProfileConfig` is configured but it is probably not defined when IntelliJ calls it to build?

But if you run your build in a fresh checkout of the source code, who is responsible of running `yarn`? It sounds like a step is missing in your build for this use case.

I also notice that you did not declare the inputs and outputs of your task. Your task will always run, even when it is not necessary (i.e the sources and configuration did not change).

I advise you to have a look to the examples I pointed, they call `yarn` to install dependencies (only when needed), build the React.js app (only when needed) and embed it to the application classpath in order to serve it.

**Comment by wonsuc** [comment]
> In the case of the return execution, the YarnTask will remain unconfigured and it will probably run an empty command, so the yarn command (not 100% sure about that). This could explain why you get a node_modules directory.

Thank you, now I understood why it happened.  

I have one more question, is there any way I can skip the `YarnTask` in the `task`?  

```
task appYarnBuild(type: YarnTask) {
    if (invalidCondition) {
        // Don't continue YarnTask.
    }
}
```

Since as you told, `return` execution will still run the `yarn` command, I wonder if there's a way to skip current task.

**Comment by deepy** [comment]
Sure there's [.onlyIf](https://docs.gradle.org/current/dsl/org.gradle.api.Task.html#org.gradle.api.Task:onlyIf(groovy.lang.Closure)) on tasks

**Comment by wonsuc** [comment]
@deepy Thank you!
