### ISSUE TITLE
Support allowInsecureProtocol

### ISSUE THREAD

**Issue by markslater** [node-gradle/gradle-node-plugin#163]
Setting distBaseUrl to an HTTP URL (for me, using Artifactory over HTTP as a proxy is a corporate requirement) causes a warning using Gradle 6.8.3 and gradle-node-plugin 3.0.1:

> Using insecure protocols with repositories, without explicit opt-in, has been deprecated.  This is scheduled to be removed in Gradle 7.0.  Switch Ivy repository [etc]

Sure enough, upgrading to Gradle 7.0 causes my build to fail.

This can be rectified by exposing [allowInsecureProtocol](https://docs.gradle.org/6.8.3/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol) on [the Ivy repository](https://github.com/node-gradle/gradle-node-plugin/blob/5e7341e0927f618ac9e9057d97588db4c8b9139a/src/main/kotlin/com/github/gradle/node/NodePlugin.kt#L89).

I'd be happy to submit a PR.

**Comment by bsautel** [comment]
Thanks for reporting this issue!

As a workaround, I suggest to set `distBaseUrl` to `null` and declare yourself the `ivy` repository in which you can set `allowInsecureProtocol` to `true`. [Here](https://github.com/node-gradle/gradle-node-plugin/blob/90871839a706cfe0262492091f301afdcfb8d1e4/docs/faq.md#is-this-plugin-compatible-with-centralized-repositories-declaration) is how to declare a Node.js `ivy` repository. The `dependencyResolutionManagement` is not mandatory, I am only talking about the `ivy` part that can be added to the `build.gradle` file.

How would you want to fix this issue? Always adding `alwaysInsecureProtocol` to `true` is simple but not very satisfying since that would block this security improvement on Gradle's side. We should probably add a flag to `NodeExtension` to force allowing insecure protocol?

**Comment by markslater** [comment]
Thanks for the pointer to the workaround.  I can confirm that fixes the issue.

I'm happy enough to live with the workaround, but I have created PR #164 with a change to add a flag to `NodeExtension` that is passed through to the `IvyRepository` that is created, if you're interested in having this feature.  Let me know what you think.

**Comment by deepy** [comment]
Coming in 3.2
