### ISSUE TITLE
Cache "node_modules" in ".gradle" folder

### ISSUE THREAD

**Issue by sergeykad** [node-gradle/gradle-node-plugin#177]
Is it possible to cache the `node_modules` folder under `.gradle` folder together with `nodejs` and `yarn`?
Why is it getting special treatment and placed in the root directory of the module?

**Comment by deepy** [comment]
The location of node_modules is determined by nodejs (see [this](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders) for a description of the rules).

If you don't need to use a npm version different than the one bundled in node and you don't do a yarn/npm install you could disable `npmSetup`/`yarnSetup` and not `node_modules` be created.

But otherwise the general idea of nodejs projects is that you have a `node_modules` next to your `package.json` and this plugin is not the one requiring this convention, rather we have to accommodate it to the best of our ability as it's how everyone does it

**Comment by sergeykad** [comment]
Thanks for clarifying it @deepy . I am asking since I am not sure how to manage the `node_modules` folder. If it was under `.gradle` then it is clearly Gradle managed and I should not touch it. However, since it is not I am not sure how to handle it. For example, should the `clean` task remove this folder?

**Comment by deepy** [comment]
I'd add it to `.gitignore` and then ask my team about if it should be removed by `clean` or not, it's a matter of preference and if in doubt then the most "correct" way is to add it to `clean`.

However, as `npmInstall` tends to be the slowest part of the process you might not want to add it to `clean` so on a clean checkout (or on something like `git clean -fdx`) run your build with `--scan` (for a good report that's published online) or `--profile` (for a less comprehensive offline HTML report) and see how long `npmInstall` takes (or in our case, `npmInstall` and `npmRunDist`) if it's short you can probably just add it to clean without worrying, if it takes 2-3 minutes like it does for us, you probably don't want to.
