### ISSUE TITLE
Plugin [id: 'com.github.node-gradle.node', version: '3.0.0'] was not found in any of the following sources:

### ISSUE THREAD

**Issue by kolotyluk** [node-gradle/gradle-node-plugin#180]
This seems to be a common problem with Gradle in general, but I never know how to resolve it because the diagnostics are misleading...

```
plugins {
    id "com.github.node-gradle.node" version "3.0.0"
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}
. . .
```

When I restart IntelliJ it complains
```
Build file '/Users/ekolotyluk/dev/crypto/customer-js/build.gradle' line: 4

Plugin [id: 'com.github.node-gradle.node', version: '3.0.0'] was not found in any of the following sources:

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.github.node-gradle.node', version: '3.0.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.node-gradle.node:com.github.node-gradle.node.gradle.plugin:3.0.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:222)
. . .
```

It seems about 50% of the time I try adding a new plug-in to Gradle, I get the same error...

Any help or advice would be greatly appreciated.

**Comment by deepy** [comment]
A year ago you could probably have heard me swear about how unreliable the plugin portal could be, but lately it's been rock-solid, at least for me.

You might have to run with `--info` or `--debug` to get a sensible error message, but if you got access to nexus, artifactory, or similar you could mirror it and use [an init-script](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management) to point to that.
But without knowing any more details all I can say is that this is likely a problem with gradle or your environment and you might want [to upgrade to 3.0.1](https://github.com/node-gradle/gradle-node-plugin/blob/master/CHANGELOG.md#version-301-2021-02-09)

**Comment by kolotyluk** [comment]
I finally got things working with 3.1.0...

Part of the problem is we are new to using Artifactory, and it routinely causes problems... for example, it kept returning 401 & 403 responses for no good reason... I had to bypass Artifactory to get things working... then IntelliJ freaks out, requiring cache invalidation and restarts until it's sane again... Even though Artifactory could see `"com.github.node-gradle:gradle-node-plugin:3.1.0"` it would not cache it??? Overall, Artifactory is much harder to use than Nexus or AWS CodeArtifact.

Part of the problem is I have a multi-module Gradle project, and the documentation here does not seem to apply... I finally got things working in the root `build.gradle` with

```
buildscript {
    dependencies {
        classpath 'com.github.node-gradle:gradle-node-plugin:3.1.0'
    }
}

allprojects {
    apply plugin: 'com.github.node-gradle.node'
}
```

It's not just this project, but many plugins do not document Gradle in a way that Gradle newbies can easily understand the abstruse intricacies of Gradle. It might help if you could document the mult-module configuration I have shown here...

I used to think Maven was hard to use, but I have experienced far more misery with Gradle.

**Comment by deepy** [comment]
I can highly recommend the new `plugins {}` syntax instead of the old with `buildscript` and `apply`, but if you do use the old syntax, only apply it in the projects where you actually have node tasks.

And honestly, I'd say we have somewhat extensive documentation, we have descriptions of how to use the tasks and the plugin in `docs` folder and we have self-contained examples in the `examples` folder.

If you've got a multi-module project but only use node/npm/yarn in one of them, the examples and the documentation should translate perfectly, if you're using it in multiple places you should add it to each project without the version, and to the root project with a version but `apply false` as described here https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl

But if you could elaborate on what part of the documentation you were having troubles with we can of course expand those areas or add links to relevant guides on Gradle's website
