### ISSUE TITLE
cannot import com.github.gradle.node.npm.task.NpmTask

### ISSUE THREAD

**Issue by Kerr0220** [node-gradle/gradle-node-plugin#188]
Excuse me. Why I cannot import it? 
I'm using Kotlin + Spring boot as backend and react as frontend.
<img width="604" alt="Screen Shot 2021-08-13 at 2 11 50 PM" src="https://user-images.githubusercontent.com/48152969/129313000-24b417bf-dc70-4903-bcaf-afc23c02a063.png">

**Comment by Kerr0220** [comment]
I'm using Gradle7

**Comment by deepy** [comment]
Have you reloaded Gradle projects in intellij after adding the plugin?
![image](https://user-images.githubusercontent.com/905507/129403240-27aea958-d556-4a87-bbf3-95d8774a6dd3.png)

Also when using kotlin for buildscripts you mostly have to use the `args.set(List)` syntax rather than `args = List`, you can see some examples here [3.1.0/src/test/resources/fixtures/kotlin/build.gradle.kts#L101](https://github.com/node-gradle/gradle-node-plugin/blob/3.1.0/src/test/resources/fixtures/kotlin/build.gradle.kts#L101)

**Comment by Kerr0220** [comment]
Oh! Thanks🙏. Reloading Gradle projects works!
