### ISSUE TITLE
gradle-node-plugin Resource missing in plugins.gradle.org 

### ISSUE THREAD

**Issue by aggaton** [node-gradle/gradle-node-plugin#277]
Have started getting these errors today, this worked fine yesterday. 

Resource missing. [HTTP HEAD: https://plugins.gradle.org/m2/com/github/node-gradle/node/com.github.node-gradle.node.gradle.plugin/2.2.4/com.github.node-gradle.node.gradle.plugin-2.2.4.jar]

If I do a wget on that url I get a 404

There seem a number of other libraries with the same issue.

**Comment by deepy** [comment]
The plugin portal is unfortunately handled outside the project, but that specific URL seems off to me, that looks like the coordinates for the [plugin marker artifacts](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers) rather than the plugin itself which resides under https://plugins.gradle.org/m2/com/github/node-gradle/gradle-node-plugin/2.2.4/
What Gradle version are you using and how are you declaring the plugin dependency?
