### ISSUE TITLE
npmInstall running when not needed

### ISSUE THREAD

**Issue by slatin-esteco** [node-gradle/gradle-node-plugin#324]
I have in the build.gradle a NpmTask that launch automatically a script in the package.json. My problem is that I am changing npm to pnpm and the plugin when it detects changes in the package.json launch npmInstall but It mustn't do this. Is there a way to override the npmInstall with pnpmInstall, block the npmInstall or set node to absolutely not use npm but use pnpm?

Node settings:
![image](https://github.com/user-attachments/assets/ca0e0ab7-1e95-4aca-8f51-6cc9f23151a4)
One of the incriminated tasks
![image](https://github.com/user-attachments/assets/5d6d083f-db79-4ae5-8cb3-c54d586e77af)
The relative script in package.json:
![image](https://github.com/user-attachments/assets/4c606901-c048-40ca-ab0c-e19935907fac)

The node that I install doesn't have pnpm but I don't think it is the real problem

**Comment by slatin-esteco** [comment]
unfortunatly `pnpm_run` doesn't exist if I am correct (I tried and searched online). To resolve the problem I am changing every task I have by registering tasks with the `PnpmTask` set like this:
![image](https://github.com/user-attachments/assets/9388f547-4117-46c9-a573-da4aea6ecb6c)
But the old method that invoked automatically the npm scripts was easier to use for me

**Comment by deepy** [comment]
Having tested it on a clean copy of `7.1.0` the `pnpm_` rules behave just like the `npm_` rules so a search and replace should work
And if you don't need the dependency on `pnpmInstall` use the `pnpm_` rule rather than the `pnpm_run_` one

But regardless, I'd still recommend defining the task like you've done above, it's the same amount of lines and only 27 characters more than relying on the rule
