### ISSUE TITLE
Document how to use grunt/gulp (as NpxTasks)

### ISSUE THREAD

**Issue by Jonatha1983** [node-gradle/gradle-node-plugin#52]
Hi - wanted to know if there are any suggestions in case someone do need to use grunt with gradle 6.0 ? 

Thanks

**Comment by deepy** [comment]
How much of grunt are you using?
If it's a simple use-case I'd create a `NpxTask` and specify `inputs`/`outputs`

**Comment by Jonatha1983** [comment]
@deepy  Thanks.

I tried to create one:
```
plugins {
    id 'distribution'
    id "com.github.node-gradle.node" version "2.0.0"
}
....
task generateGrunt(type: NpxTask) {
    command = '@grunt-cli@"^1.3.2'
    args = [ 'myApp']
}
```
And got:
```
A problem occurred evaluating project ':grunt-module'.
> Could not get unknown property 'NpxTask' for project
``` 

Thanks again

**Comment by deepy** [comment]
@Jonatha1983 NpxTask is new in 2.1.0 but you should use 2.2.0 (or 2.1.1)

**Comment by Jonatha1983** [comment]
In this case I suggest to change the doc to the correct version.

**Comment by deepy** [comment]
I guess what we really should do is document on how to use `NpxTask` for grunt/gulp

**Comment by bsautel** [comment]
@Jonatha1983 , I would recommend you to add `grunt-cli` to your `package.json` file so that it is automatically installed by the `npmInstall` and change the `generateGrunt` command to `grunt`.

This will make the `generateGrunt` task faster because `npx` will use the locally installed `grunt-cli` instead of downloading and installing each time.
