### ISSUE TITLE
Gradle directs you to the old plugin

### ISSUE THREAD

**Issue by myronu** [node-gradle/gradle-node-plugin#75]
Just a simple request. We didn't know that the plugin had been moved to a new location and was still being developed, thus we didn't know that we needed to update our gradle scripts. There is nothing in the old project that points to the new project. There are also lots of examples on the web referencing your project by its old com.moowork.node name.

A simple edit to the old readme.md pointing to the new project would be of great use to anybody looking to write new build scripts.

**Comment by deepy** [comment]
Unfortunately we have no control over the old project, it's seemingly abandoned even though srs popped in a year ago saying he's open to additional collaborators.

I started this fork initially because at work we needed this functionality and Gradle 5 support, and srs' plugin worked great for us.
With that said I'm committed to the community around this (well, both) plugins :-)
