### ISSUE TITLE
.npmrc not recognized

### ISSUE THREAD

**Issue by bbajor** [node-gradle/gradle-node-plugin#91]
Hello, i tried npmInstall using a local .npmrc file as follows:
`registry=path/to/nexus/npm
_auth=authKey
email=myEmail
strict-ssl=false
always-auth=true
cafile=keystore.pem
` 
but when invoking npmSetup, i get following error:
`
> Task :npmSetup FAILED
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/npm failed, reason: connect ECONNREFUSED 
`
Do you know, what went wrong?

**Comment by deepy** [comment]
Is your `.npmrc` having all of the settings on the same line?
Mine looks like this:
```ini
registry=https://nexus.example.com/...
always-auth=true
_auth=31pfen1fheih1fij==
```

**Comment by bbajor** [comment]
It looks like yours, i didn't format it sorry.

**Comment by bsautel** [comment]
Where is located your `.npmrc` file?

**Comment by bbajor** [comment]
The `.npmrc` is located at the root of my project directory. I configured node as described [here](https://github.com/node-gradle/gradle-node-plugin/blob/master/docs/node.md#configuring-the-plugin)
and also tried this [workaround](https://github.com/srs/gradle-node-plugin/issues/298#issuecomment-559168392), but it didn't work. Do you have an idea, where it should be located?

**Comment by bsautel** [comment]
On my side I have a `.npmrc` file in the `$HOME` directory and it works through the plugin.

According to [the documentation](https://docs.npmjs.com/files/npmrc), the `.npmrc` file can be located at the project root, so its location seems to be good.

Did you try executing commands in your project manually (without the plugin)? That would enable to know whether the issue comes from the plugin or not.

I don't see any specific reason that could explain why this file is ignored, the plugin runs `npm` commands as you would do. The `.npmrc` is processed internally by `npm`, so it should be done whether it is run manually or by the Gradle plugin.

**Comment by bbajor** [comment]
When put into user home, it worked for me, while the project root location did not. Thanks for fast help :)

**Comment by bsautel** [comment]
You're welcome! Did you try launching manually `npm` to ensure that the problem does not come from the plugin?

**Comment by bbajor** [comment]
Yes it worked. The plugin also works, if no configuration mentioned under [Node Configuration](-PmvnSettingsLocation=C:/Entwicklung/Programme/apache-maven-3.6.3-bin/settings/settings.xml --warning-mode=all ) has been set.

**Comment by bsautel** [comment]
You mean you first copied the whole configuration?

**Comment by bbajor** [comment]
I think we can close this one. I tried again without custom configuration and using the Vaadin-Plugin and in both cases, it worked. It must have been a layer 8 problem^^ Nevertheless i have to thank you for your questions, that helped me a lot!

**Comment by bsautel** [comment]
You are welcome!
