### ISSUE TITLE
npm_run_start task ends quickly

### ISSUE THREAD

**Issue by somebodil** [node-gradle/gradle-node-plugin#97]
npm_run_start task run successfully, and it ends quickly.

It should not end until user ends the process.

![image](https://user-images.githubusercontent.com/4278906/80551917-0b279d00-8a00-11ea-9e54-8a2d8cc46930.png)

Is it possible that npm_run_start task run like "bootRun" task in spring-boot.

----------------------- updated ------------------------

I should have gave more information.

I'm following below link, which is introducing how to integrate java-app (spring boot) and npm-app (create-react-app).
https://dzone.com/articles/integrating-java-and-npm-builds-using-gradle

Unlike in the link, I "used node-gradle/gradle-node-plugin" plugin.

But when I did "gradle npm_run_start", it ends like above image.

If I run via command directly, it works successfully.

![image](https://user-images.githubusercontent.com/4278906/80671605-58316f00-8ae5-11ea-980f-9aa97c54e566.png)

**Comment by bsautel** [comment]
What does the `start` `npm` script? Something like `webpack serve`?

What happens if you run this command out of the plugin?

Note that there is a known issue when using server commands (that don't end until you type Ctrl-C) such as `webpack serve`. When you stop Gradle using Ctrl-C, the subcommand is not stopped. See #65 for that.

**Comment by somebodil** [comment]
@bsautel Thanks for the fast reply. I updated my comment above. Please check :)

**Comment by bsautel** [comment]
I don't know why the `npm_run_start` stops before starting the server. But as I explained, I would not recommend you using Gradle to run the development service since you won't be able to stop it because of #65. I would recommend you to run this command by hand, by using `npm start` or `npx react-scripts start`.

**Comment by somebodil** [comment]
@bsautel thank you~
